// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hashmess.proto

package hashmess

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Comment struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9672b0d27f527f, []int{0}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Comment) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CommentsRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentsRequest) Reset()         { *m = CommentsRequest{} }
func (m *CommentsRequest) String() string { return proto.CompactTextString(m) }
func (*CommentsRequest) ProtoMessage()    {}
func (*CommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9672b0d27f527f, []int{1}
}

func (m *CommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsRequest.Unmarshal(m, b)
}
func (m *CommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsRequest.Marshal(b, m, deterministic)
}
func (m *CommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsRequest.Merge(m, src)
}
func (m *CommentsRequest) XXX_Size() int {
	return xxx_messageInfo_CommentsRequest.Size(m)
}
func (m *CommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsRequest proto.InternalMessageInfo

func (m *CommentsRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Comments struct {
	Comments             []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Comments) Reset()         { *m = Comments{} }
func (m *Comments) String() string { return proto.CompactTextString(m) }
func (*Comments) ProtoMessage()    {}
func (*Comments) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9672b0d27f527f, []int{2}
}

func (m *Comments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comments.Unmarshal(m, b)
}
func (m *Comments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comments.Marshal(b, m, deterministic)
}
func (m *Comments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comments.Merge(m, src)
}
func (m *Comments) XXX_Size() int {
	return xxx_messageInfo_Comments.Size(m)
}
func (m *Comments) XXX_DiscardUnknown() {
	xxx_messageInfo_Comments.DiscardUnknown(m)
}

var xxx_messageInfo_Comments proto.InternalMessageInfo

func (m *Comments) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func init() {
	proto.RegisterType((*Comment)(nil), "hashmess.Comment")
	proto.RegisterType((*CommentsRequest)(nil), "hashmess.CommentsRequest")
	proto.RegisterType((*Comments)(nil), "hashmess.Comments")
}

func init() { proto.RegisterFile("hashmess.proto", fileDescriptor_2d9672b0d27f527f) }

var fileDescriptor_2d9672b0d27f527f = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x48, 0x2c, 0xce,
	0xc8, 0x4d, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xcc,
	0xb9, 0xd8, 0x9d, 0xf3, 0x73, 0x73, 0x53, 0xf3, 0x4a, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x8b, 0x53,
	0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0x76, 0x90, 0xb2,
	0xc4, 0xf4, 0x54, 0x09, 0x26, 0xb0, 0x30, 0x8c, 0xab, 0xa4, 0xca, 0xc5, 0x0f, 0xd5, 0x58, 0x1c,
	0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x0c, 0x36, 0x00, 0x64, 0x2e, 0xcc, 0x00, 0x10, 0x5b, 0xc9, 0x92,
	0x8b, 0x03, 0xa6, 0x4c, 0x48, 0x97, 0x8b, 0x23, 0x19, 0xca, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0,
	0x36, 0x12, 0xd4, 0x83, 0x3b, 0x0c, 0xaa, 0x2a, 0x08, 0xae, 0xc4, 0x28, 0x10, 0x61, 0x43, 0x70,
	0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x1d, 0x17, 0xb7, 0x7b, 0x6a, 0x09, 0xdc, 0x40, 0x49,
	0x0c, 0xed, 0x30, 0xb7, 0x48, 0x09, 0x61, 0x4a, 0x29, 0x31, 0x24, 0xb1, 0x81, 0xbd, 0x6f, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x9b, 0x89, 0xe1, 0x10, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommentsServiceClient is the client API for CommentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentsServiceClient interface {
	GetComments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*Comments, error)
}

type commentsServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommentsServiceClient(cc *grpc.ClientConn) CommentsServiceClient {
	return &commentsServiceClient{cc}
}

func (c *commentsServiceClient) GetComments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*Comments, error) {
	out := new(Comments)
	err := c.cc.Invoke(ctx, "/hashmess.CommentsService/GetComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentsServiceServer is the server API for CommentsService service.
type CommentsServiceServer interface {
	GetComments(context.Context, *CommentsRequest) (*Comments, error)
}

// UnimplementedCommentsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommentsServiceServer struct {
}

func (*UnimplementedCommentsServiceServer) GetComments(ctx context.Context, req *CommentsRequest) (*Comments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComments not implemented")
}

func RegisterCommentsServiceServer(s *grpc.Server, srv CommentsServiceServer) {
	s.RegisterService(&_CommentsService_serviceDesc, srv)
}

func _CommentsService_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServiceServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashmess.CommentsService/GetComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServiceServer).GetComments(ctx, req.(*CommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommentsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashmess.CommentsService",
	HandlerType: (*CommentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetComments",
			Handler:    _CommentsService_GetComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashmess.proto",
}
